### ISSUE TITLE
*revives*

### ISSUE THREAD

**Issue by staticvoidliam7** [Eitantan/IridiumLang#12]

**Comment by Eitantan** [comment]
do you want to keep working on it?

**Comment by staticvoidliam7** [comment]
Yes

**Comment by Eitantan** [comment]
ok go on repl.it tomorrow at 5:30 mst

**Comment by staticvoidliam7** [comment]
If you're available now I can hop on

**Comment by vghfr** [comment]
Before we continue, we need to organize the files in such a way that it will work with repl.it and have both versions avaliable
